export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';

export const GET_APARTMENTS_REQUEST = 'GET_APARTMENTS_REQUEST';
export const GET_APARTMENT_REQUEST = 'GET_APARTMENT_REQUEST';
export const ADD_APARTMENT_REQUEST = 'ADD_APARTMENT_REQUEST';
export const UPDATE_APARTMENT_REQUEST = 'UPDATE_APARTMENT_REQUEST';
export const DELETE_APARTMENT_REQUEST = 'DELETE_APARTMENT_REQUEST';
